### ISSUE TITLE
`currentIndex` is not always getting reported correctly in events

### ISSUE THREAD

**Issue by Jon-Salmon** [bdlukaa/just_audio#15]
**Which API doesn't behave as documented, and how does it misbehave?**
`AudioPlayer::broadcastPlaybackEvent` doesn't set the `currentIndex` parameter correctly.

**Minimal reproduction project**
Subscribe to the `playbackEventMessageStream` stream on an audio player instance, and observe the state of the `currentIndex` parameter (when the playback type is not `concatenating`).

**To Reproduce (i.e. user steps, not code)**
Subscribe to the `playbackEventMessageStream` stream on an audio player instance, and observe the state of the `currentIndex` parameter (when the playback type is not `concatenating`).

**Error messages**
This doesn't directly cause error messages, but breaks integration with `just_audio_background`

**Expected behavior**
The `currentIndex` should be set to 0 when the media is playing.

**Screenshots**
Things seem to be better behaved if I make the changes:
![image](https://user-images.githubusercontent.com/26483285/206322702-650f0ab1-d4d2-46f8-8bc0-ef48e9474962.png)
such that `mediaPlaybackList` is always updated, but I don't have enough of an understanding of what everything else is doing to know what affect this will have on the rest of the plugin's operation.

**Desktop (please complete the following information):**
 - OS: Windows

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22621.819], locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by bdlukaa** [comment]
Does #16 fix the issue?

**Comment by Jon-Salmon** [comment]
Yes, that fixes it. Thanks
