### ISSUE TITLE
Unable To Play AAC-LC Encoding Files

### ISSUE THREAD

**Issue by kuroodo** [bdlukaa/just_audio#18]
**Which API doesn't behave as documented, and how does it misbehave?**
I am trying to use the [record package](https://pub.dev/packages/record) to record microphone audio, and then play it. I am encoding the audio file using the AAC-LC encoder that the package provides. The audio file is saved as an m4a, and it works well. The audio file can be read and played on an android application using the just_audio no problem.

But on desktop, with just_audio_windows the file is unable to be read

**Minimal reproduction project**
The Example project.
Use AudioSource.file to load this file: https://drive.google.com/file/d/1e9i7WGS9qQFFDjPj9E-QPD24A32ta_8P/view?usp=share_link

**To Reproduce (i.e. user steps, not code)**
1. Run the project

**Error messages**

```
[just_audio_windows] Media error:
flutter: Error loading audio source: Loading interrupted
```

**Expected behavior**
The audio file is read. It can be played, paused, and time should be visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 13

**Flutter SDK version**
Ignore the Android Studio warning
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19044.2728], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.0)
[√] Android Studio (version 2021.2)
[!] Android Studio (version 4.1)
    X Unable to determine bundled Java version.
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.77.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by bdlukaa** [comment]
Hello! Can you confirm the AAC-LC codec is installed on your device? (See [query codec](https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/codec-query)) You can check that on System Information -> Multimedia -> Audio Codecs

By default, AAC-LC decoded should be installed in your device.
https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/supported-codecs

**Comment by kuroodo** [comment]
I use [MPC-HC](https://mpc-hc.org/) to play audio, so that's why I am able to play it. However when using the default players that come with Windows (such as windows media player) they are unable to play it and throw an error. Therefore I believe the codec is not installed on the OS itself. It appears that Windows 11 has built in support for this, but Windows 10 does not.

If that's the case, then this is probably not a bug but rather an issue on my end. I guess I'll have to find a way to encode to mp3 or some other work around in order to ensure a proper user experience.
