### ISSUE TITLE
Issue with space in File Path for "just_audio_windows"

### ISSUE THREAD

**Issue by fvthakor** [bdlukaa/just_audio#25]
**Description:**
When attempting to load audio files with space in their names, such as "C:\Users\HP\Downloads\Ve Kamleya Rocky Aur Rani Kii Prem Kahaani 320 Kbps.mp3" the "just_audio_windows" seems to encounter issues.

**Steps to Reproduce:**
- Install the latest version of "just_audio_windows."
- Use the following code to load an audio file with a space name:
 ```
await _player.setAudioSource(AudioSource.uri(Uri.parse(path)));
```

**Expected Behavior:**
The "just_audio_windows" and "just_audio" should load and play audio files with space in their names without any errors.

**Actual Behavior:**
[just_audio_windows] Item error: The system cannot find the path specified.
Instead, the audio player throws an exception or fails to load the file properly when space are present in the file name.

**Environment:**
just_audio : ^0.9.34
just_audio_windows: any

Flutter version: 3.10.6
Operating System: Windows 11

![image](https://github.com/bdlukaa/just_audio_windows/assets/42373267/992146d3-514b-49e2-a5bf-e114352b17fe)

**Comment by gstory0404** [comment]
Encountered the same problem, have you solved it? @fvthakor
