### ISSUE TITLE
Inquiry about Minimum Supported Windows SDK Version

### ISSUE THREAD

**Issue by akindone** [bdlukaa/just_audio#28]
**To which pages does your suggestion apply?**

- [Direct URL 1](https://github.com/bdlukaa/just_audio_windows/blob/master/just_audio_windows/README.md)
Add `Target platform requirements` section

**Quote the sentences(s) from the documentation to be improved (if any)**

> Insert here. (Skip if you are proposing an entirely new section.)

**Describe your suggestion**
Hello,

I am interested in using the `[just_audio_windows]` plugin for a project that targets Windows. Before I proceed, I would like to confirm the minimum supported version of the Windows SDK required by this plugin to ensure compatibility with my development environment and target Windows platforms.

I have checked the `CMakeLists.txt` and other documentation but could not find specific information regarding the Windows SDK version. 
Could you please provide some guidance on the minimum Windows SDK version that is compatible with the [just_audio_windows] plugin? This information will be very helpful for setting up my development environment correctly.

Thank you for your assistance and for the work you've put into this plugin.

Best regards

**Comment by bdlukaa** [comment]
This should work on every UWP app, which basically means Windows 10 or later and X-Box.

https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/media-playback#media-playback-sdk-samples
