### ISSUE TITLE
Audio balance is set to right channel only

### ISSUE THREAD

**Issue by Sn8z** [bdlukaa/just_audio#4]
**Which API doesn't behave as documented, and how does it misbehave?**
[setPitch()](https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setPitch.html)
The setPitch function changes the audio balance instead of the pitch.

**Minimal reproduction project**
[Minimal reproduction](https://github.com/Sn8z/just_audio_windows_repro)

**To Reproduce (i.e. user steps, not code)**
1. Build the project for windows
2. Click on Play
3. Observe audio only coming from the right channel
4. Use the different buttons to change pitch
5. Observe audio balance changing instead of pitch

**Expected behavior**
With a default player I expect the audio to be stereo as in the case with just_audio for other platforms.
I also expect the setPitch() function to change the pitch instead of audio balance.

**Screenshots**
https://user-images.githubusercontent.com/10712909/195821286-47bc0263-5a9f-4aca-9c29-bc023ccf7645.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22621.674], locale en-SE)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.72.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

**Additional context**
Looking through the code in player.hpp it seems to me that [this](https://github.com/bdlukaa/just_audio/blob/d8a52f371cd04c81938f262b31a2a6c34245a636/just_audio_windows/windows/player.hpp#L202-L209) part is the cause.

[AudioBalance](https://learn.microsoft.com/is-is/uwp/api/windows.media.playback.mediaplayer.audiobalance?view=winrt-18362) as described here seems to not change the pitch, unfortunately I couldn't find an alternative for it.

**Comment by Fraa-124** [comment]
This is also happening to me

**Comment by Sn8z** [comment]
@bdlukaa is there any update or feedback on this issue?

**Comment by Sn8z** [comment]
Actually, after some more research this issue is now gone and seems to be fixed by #8 
Not sure if intended or not but a mention would have been sweet, either way I'm happy 😄 
Thanks for your work @bdlukaa

**Comment by bdlukaa** [comment]
`setPitch` is actually not implemented. See https://github.com/bdlukaa/just_audio_windows/blob/master/just_audio_windows/windows/player.hpp#L274-L275

**Comment by Sn8z** [comment]
Actually, you had an implementation for it before #8 as can be seen [here](https://github.com/bdlukaa/just_audio_windows/blob/d8a52f371cd04c81938f262b31a2a6c34245a636/just_audio_windows/windows/player.hpp#L202-L209) which I also linked to when opening the issue..
#8 removed this implementation without mentioning it and it also seemed to have been merged without anyone noticing it.
So there was an implementation for setPitch() which actually changed the balance instead.
[Here](https://github.com/bdlukaa/just_audio_windows/pull/8/commits/2e6929212c9b4d4de2743f66c7b0d6f794b33275#diff-31c5fe48a87e81a2e25b5a5c36cd79e2347350d93825ae546521cc11239645b0L202-L209) it gets removed and [here](https://github.com/bdlukaa/just_audio_windows/pull/8/commits/2e6929212c9b4d4de2743f66c7b0d6f794b33275#diff-31c5fe48a87e81a2e25b5a5c36cd79e2347350d93825ae546521cc11239645b0R274-R275) is the implementation removed.
